export const UPDATE_SELECTED_CARD = 'UPDATE_SELECTED_CARD';
export const SAVE_WEATHER_DATA = 'SAVE_WEATHER_DATA';
export const UPDATE_TEMP_SCALE = 'UPDATE_TEMP_SCALE';
export const ERROR_LOADING_DATA = 'ERROR_LOADING_DATA';

export default {
	UPDATE_SELECTED_CARD,
	SAVE_WEATHER_DATA,
	UPDATE_TEMP_SCALE,
	ERROR_LOADING_DATA,
};
